### ISSUE TITLE
massive spam in server log after update PeiAI&cats&wolfs to 1.4.0 

### ISSUE THREAD

**Issue by cyraxan** [G3rste/petai#33]
19:15:43 [Server Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at PetAI.EntityBehaviorTameable.OnEntityDespawn(EntityDespawnReason despawn)
   at Vintagestory.API.Common.Entities.Entity.OnEntityDespawn(EntityDespawnReason despawn)
   at Vintagestory.Server.ServerMain.DespawnEntity(Entity entity, EntityDespawnReason reason)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()

**Comment by G3rste** [comment]
Is there an initial exception prior to this?
Is there action you have done before the serverlog got spammed?

**Comment by NovaNine** [comment]
We are getting this as well, and cannot play at all (essentially it starts happening as soon as a player logs in)

Best we can tell, this happened when one of our players was putting some limonite nuggets in a bloomery.  However it's probably much more likely tied to the tamed Cats nearby.  We just updated Cats + PetAI earlier today to latest versions.

**Comment by NovaNine** [comment]
As best as I can see, there is no previous exception between the server starting and this (we don't have the log from the original crash):

From `logs/server-main.txt`:
```
3.4.2022 20:19:44 [Event] Praal [::ffff:192.168.0.1]:2755 joins.
3.4.2022 20:19:48 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at PetAI.EntityBehaviorTameable.OnEntityDespawn(EntityDespawnReason despawn)
   at Vintagestory.API.Common.Entities.Entity.OnEntityDespawn(EntityDespawnReason despawn)
   at Vintagestory.Server.ServerMain.DespawnEntity(Entity entity, EntityDespawnReason reason)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
```

**Comment by G3rste** [comment]
I hope this fixes the issue.
I am going to upload this directly to the moddb too to prevent people from running into this issue.
If someone left a little feedback if it worked that would be really great. I am going to leave this Issue open until i am certain that this is handled properly.
[petai_v1.4.1.zip](https://github.com/G3rste/petai/files/8412043/petai_v1.4.1.zip)

**Comment by cyraxan** [comment]
looks like ok now, thanks!
