### ISSUE TITLE
Melee attacks on horses cause host client to crash

### ISSUE THREAD

**Issue by HawkeTheKite** [G3rste/petai#56]
Playing on single player world opened online with 3 friends. Horses do not take damage from arrows, they bounce off which I assumed was because of Don't Hit Your Pets despite horses being untamed. However when a horse is ridden into a campfire or if a wild (never fed, completely wild) horse is hit with melee (tested with a punch) my (host) game crashes but none of the other players are crashed. Will be testing on true single player later.

Certainly an issue interacting with don't hit your pets

Crash report in logs:
1/5/2024 1:44:38 AM: Critical error occurred in the following mod: petai@2.2.0
Loaded Mods: driftersbelongunderground@1.0.1, caninae@1.0.7, primitivesurvival@3.4.5, game@1.19.0-rc.4, accessibilitytweaks@3.4.1, animalcages@3.0.0, animationmanagerlib@0.2.0, BedRespawning@1.0.1, carryon@1.7.0-pre.3, coolinbarrel@0.5.3, hudclock@3.4.0, moreanimals@1.3.1, mouse4and5@1.0.0, petai@2.2.0, creative@1.19.0-rc.4, survival@1.19.0-rc.4, cats@2.0.0, feverstonehorses@1.6.0-rc.2, feverstonewilds@1.4.5, tieredtradebags@1.0.1, wolftaming@2.0.1
System.MissingMethodException: Method not found: 'Boolean PetAI.PetConfig.get_pvpOff()'.
   at DontHitYourPets.HarmonyPatches.DontHitYourPetsPatch.Prefix(EntityPet __instance, Boolean& __result, DamageSource damageSource, Single damage)
   at PetAI.EntityPet.ShouldReceiveDamage_Patch1(EntityPet this, DamageSource damageSource, Single damage)
   at PetAI.EntityMount.ShouldReceiveDamage(DamageSource damageSource, Single damage) in E:\Workspace\vintage_story_mods\petai\src\Entity\EntityMount.cs:line 106
   at Vintagestory.API.Common.Entities.Entity.ReceiveDamage(DamageSource damageSource, Single damage) in VintagestoryApi\Common\Entity\Entity.cs:line 806
   at Vintagestory.API.Common.EntityAgent.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in VintagestoryApi\Common\Entity\EntityAgent.cs:line 284
   at PetAI.EntityMount.OnInteract(EntityAgent byEntity, ItemSlot slot, Vec3d hitPosition, EnumInteractMode mode) in E:\Workspace\vintage_story_mods\petai\src\Entity\EntityMount.cs:line 96
   at Vintagestory.Client.NoObf.ClientMain.TryAttackEntity(EntitySelection selection) in VintagestoryLib\Client\ClientMain.cs:line 2684
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleMouseInteractionsNoBlockSelected(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 393
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnFinalizeFrame(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 96
   at Vintagestory.Client.NoObf.ClientEventManager.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\Util\ClientEventManager.cs:line 185
   at Vintagestory.Client.NoObf.ClientMain.TriggerRenderStage(EnumRenderStage stage, Single dt) in VintagestoryLib\Client\ClientMain.cs:line 802
   at Vintagestory.Client.NoObf.ClientMain.RenderToDefaultFramebuffer(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 1006
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 674
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 649
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 78
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 317
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 128
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

**Comment by G3rste** [comment]
looks like this is caused by another mod you have installed: DontHitYourPets.HarmonyPatches.DontHitYourPetsPatch.Prefix
