### ISSUE TITLE
Crashes with tamed cats or dogs trying to engage in combat

### ISSUE THREAD

**Issue by SmeeSlug** [G3rste/petai#9]
3.2.2022 02:44:43 [Fatal] System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.AiTaskSeekEntity.ContinueExecute(Single dt)
   at Vintagestory.GameContent.AiTaskManager.OnGameTick(Single dt)
   at Vintagestory.GameContent.EntityBehaviorTaskAI.OnGameTick(Single deltaTime)
   at Vintagestory.API.Common.Entities.Entity.OnGameTick(Single dt)
   at Vintagestory.API.Common.EntityAgent.OnGameTick(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.TickEntities(Single dt)
   at Vintagestory.Server.ServerSystemEntitySimulation.OnServerTick(Single dt)
   at Vintagestory.Server.ServerMain.Process()
this error shows up many times in very quick succession (several times every second)

**Comment by RogueRaiden** [comment]
Are you using version 1.3.2? Should be fixed in that version

**Comment by SmeeSlug** [comment]
Ah sorry! I thought I had updated, must have missed that
